### PR TITLE
Windsor Installers added

### PR DESCRIPTION
**Pull request by skoon**
Now when the Windsor service locator is created, it should scan all the assemblies for types implementing IWindsorInstaller and use the WindsorContainer.Install method to run them.

Also fixed a broken AutoFac test and implementation. At least I think I did. Heck, who knows it's AutoFac. But the tests pass. And that says something. I'm not sure what, but something.

### CODE REVIEW

**Comment by darrencauthon** [comment]
I'm glad I don't use Windsor. :)

I feel like this kinda goes against the theme of MVC Turbine, but can't argue that it's not helpful.

**Comment by skoon** [comment]
Not sure what the theme of MVC Turbine is then. Originally, it helped you by hiding all the nasty-ness of putting a DI container into MVC and making it easier to compose your application. This just extends the kind of behavior exhibited by the built in auto-registration of Filters, Binders, etc ... Dunno if the other IoC containers have this kind of interface, I think StructureMap does. But for us, using Windsor, it has simplified our container initialization. Now we just write installers that are contained in each project assembly that register the interfaces and components contained within the assembly rather than having them in a single class. It's very similar to the IServiceRegistration interface in Turbine.

**Comment by skoon** [comment]
Also my Git-fu sucks so I couldn't figure out how to re-write history and remove the commits that aren't really necessary for the final result. :/

**Comment by darrencauthon** [comment]
But that's what I mean:  MVC Turbine has an IServiceRegistration that seems to do the same as this IWindsorInstaller.  However, MVC Turbine does it in a way that is not dependent on any IoC container.  

As an example I've brought up during MVC Turbine presentations:  I can write a MVC component that I use in my Unity application, and then pass it to Javier who can use it in his Windsor applications.  

MVC Turbine doesn't just hide all of the nasty-ness of a DI container, it actually makes sharing components possible.  I can write components like MvcTurbine.FluentValidation, MvcTurbine.GoogleSiteMap, MvcTurbine.PrincipalProvider, etc. without restricting my tool to just Windsor.

I'm not arguing that this pull request should not be accepted, it is an enhancement that makes it easier to use for Windsor users.  But there are lots of features in all of the IoC containers that could be brought in, but use of those features is going to keep everybody's .Net applications like they already are:  Segregated into their own IoC container camps.

**Comment by skoon** [comment]
Right, you still can write a component that uses IServiceRegistration and not have to worry about the component. BUT, and this holds true mostly for Enterprise devs or devs working with shared libraries, there may be shared business libraries in an organization that currently use IWindsorInstaller to register their interfaces and impls. This allows those devs to more easily integrate those libraries into MVCTurbine and does not require them to take a dependency on MVCTurbine to use the IServiceRegistration interface. 

I can see your point about using IServiceRegistration, especially if you are creating components for use in Turbine. This is more for the devs that are already using Windsor and have existing libraries that make use of the IWindsorInstaller interface. It's very similar to the Facilities support that is already built into Turbine. :)

**Pull request merged**
